1. What is a Python library? Why do we use Python libraries

A Python library is a collection of pre-written code that provides specific functionality, which can be reused by developers 
to perform common tasks without having to write the code from scratch. Libraries contain modules that include functions, classes, 
and variables to help solve particular problems or implement features efficiently.
Code Reusability,Efficiency,Specialization,Community Support,Simplification,Standardization,Interoperability

2. What is the difference between Numpy array and List?

array is homogeneous and list is heterogeneous.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
import numpy as np
arr1=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr1.shape

(3, 4)

In [6]:
arr1.size

12

In [7]:
arr1.ndim

2

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [10]:
arr2=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr2[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [13]:
arr3=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

arr3[2,3]

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [18]:
arr4=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
l=[]
for i in np.nditer(arr4):
    if i%2!=0:
        l.append(i)
print(l)

[array(1), array(3), array(5), array(7), array(9), array(11)]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [29]:
arr5=np.linspace(0,1,9).reshape(3,3)
arr5

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [32]:
arr6=np.empty((3,3))
arr6

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [41]:
arr7=np.random.rand(3,3)
arr7

array([[0.1649723 , 0.53236123, 0.10211445],
       [0.59340994, 0.49151501, 0.3929773 ],
       [0.56275336, 0.04769763, 0.54967742]])

8. Describe the difference between np.random.rand and np.random.randn?

The np.random.randn function in the NumPy library generates samples from the standard normal distribution (mean = 0, standard deviation = 1).
The np.random.rand function in the NumPy library generates random numbers from a uniform distribution over the interval [0, 1). 

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [46]:
arr8=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]],ndmin=3)
arr8

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [49]:
transpose=np.transpose([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [51]:
A2=np.matrix([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B2=np.matrix( [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [54]:
A2

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [55]:
B2

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Perform the following operation using Python1
1. Indexwise multiplication

In [53]:
np.multiply(A2,B2)

matrix([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]])

2. Matrix multiplication

In [56]:
np.multiply(A2,B2)

matrix([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]])

3. add both matrix

In [57]:
np.add(A2,B2)

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

4.subtract B from A

In [58]:
np.subtract(A2,B2)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

5.divide matrix B by A

In [60]:
B2/A2

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte order of an array?

In [61]:
arr = np.array([1, 256, 65536], dtype=np.int32)
print("Original array:")
print(arr)

# Swap bytes of the array
swapped_arr = arr.byteswap()
print("\nArray with swapped bytes:")
print(swapped_arr)

Original array:
[    1   256 65536]

Array with swapped bytes:
[16777216    65536      256]


13.  What is the significance of the np.linalg.inv function?

Gives the inverse in linear algebra

In [62]:
A = np.array([[2,3,5],[3,10,15],[5,-2,7]])
B = np.array([15,40,20])

In [63]:
np.linalg.inv(A)

array([[ 1.2195122 , -0.37804878, -0.06097561],
       [ 0.65853659, -0.13414634, -0.18292683],
       [-0.68292683,  0.23170732,  0.13414634]])

14. What does the np.reshape function do, and how is it used?

It reshapes the array to required shape

In [65]:
z=np.random.randint(2,10,16).reshape(4,4)
z

array([[7, 2, 9, 8],
       [5, 8, 3, 9],
       [7, 5, 3, 3],
       [9, 8, 7, 8]])

15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows operations on arrays of different shapes.
In simple terms, broadcasting refers to the automatic expansion of arrays so that 
they have compatible shapes for element-wise operations without making copies of the data.

In [66]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([[10], [20], [30]])

print("Array A:")
print(A)

print("\nArray B:")
print(B)

# Add A and B using broadcasting
C = A + B

print("\nResult of A + B:")
print(C)


Array A:
[1 2 3]

Array B:
[[10]
 [20]
 [30]]

Result of A + B:
[[11 12 13]
 [21 22 23]
 [31 32 33]]
