1.Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each
method and the final output after each method.

In [1]:
import numpy as np

# Method 1: Using a list of lists
array_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array 1 (list of lists):\n", array_1)

# Method 2: Using `np.full`
array_2 = np.full((3, 3), [1, 2, 3])
print("Array 2 (np.full):\n", array_2)

# Method 3: Using `np.repeat`
array_3 = np.repeat([[1, 2, 3]], 3, axis=0)
print("Array 3 (np.repeat):\n", array_3)

Array 1 (list of lists):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2 (np.full):
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Array 3 (np.repeat):
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


2.Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10.
Reshape that 1D array into a 2D array.

In [5]:
# Generate 100 numbers between 1 and 10 and reshape into 2D array
array_2d = np.linspace(1, 10, num=100).reshape(10,10)
print(array_2d)

[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.09090909  8.18181818]
 [ 8.272

3. Explain the following terms-

A. The difference in np.array, np.asarray and np.asanyarray.

B. The difference between Deep copy and shallow copy.

A. Numpy array VS Numpy asarray-

In Python, NumPy array and NumPy asarray are used to convert the data into ndarray. If we talk about the major difference that is when we make a NumPy array using np.array, it creates a copy of the object array or the original array and does not reflect any changes made to the original array.
Whereas on the other hand, when we try to use NumPy asarray, it would reflect all the changes made to the original array.

numpy.asanyarray()function is used when we want to convert input to an array but it pass ndarray subclasses through. Input can be scalars, lists, lists of tuples, tuples, tuples of tuples, tuples of lists and ndarrays.

B. Deep copy in Python-

A deep copy creates a new compound object before inserting copies of the items found in the original into it in a recursive manner.
It will first construct a new collection object and then recursively populate it with copies of the child objects found in the original. It means that any changes made to a copy of the object do not reflect in the original object.

Shallow copy in Python-

A shallow copy creates a new object but retains references to the objects contained within the original. It only copies the top-level structure without duplicating nested elements.
Changes made to a copy of an object do reflect in the original object. In python, this is implemented using the “copy.copy()” function.

4. Generate a 3x3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.

In [7]:
# Generate a 3x3 array with random floating-point numbers between 5 and 20
random_array = np.random.uniform(5, 20, (3, 3))

# Round each number to 2 decimal places
rounded_array = np.round(random_array, 2)

print(rounded_array)

[[19.3  12.02 15.71]
 [ 5.83 11.23 15.35]
 [ 5.63 16.63 18.09]]


5. Create a NumPy array with random integers between 1 and 10 of shape (5, 6). After creating the array
perform the following operations:

 a)Extract all even integers from array.

 b)Extract all odd integers from array.

In [11]:
import numpy as np

# Create a 5x6 array with random integers between 1 and 10
array = np.random.randint(1, 11, size=(5, 6))

print("Original Array:")
print(array)

# Extract all even integers
even_numbers = array[array % 2 == 0]

print("\nEven Integers:")
print(even_numbers)

# Extract all odd integers
odd_numbers = array[array % 2 != 0]

print("\nOdd Integers:")
print(odd_numbers)

Original Array:
[[ 9 10  8  5  2 10]
 [ 5 10  6  7  7  3]
 [ 6  4  7  7  1 10]
 [ 5  4  9  4  6  7]
 [ 9  1  3  7  6  6]]

Even Integers:
[10  8  2 10 10  6  6  4 10  4  4  6  6  6]

Odd Integers:
[9 5 5 7 7 3 7 7 1 5 9 7 9 1 3 7]


6. Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the
following operations:

 a) Find the indices of the maximum values along each depth level (third axis).

 b) Perform element-wise multiplication of between both array.

In [12]:
# Create a 3D array of shape (3, 3, 3) with random integers between 1 and 10
array_3d = np.random.randint(1, 11, size=(3, 3, 3))
print("3D Array:\n", array_3d)

# Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array_3d, axis=2)
print("\nIndices of maximum values along each depth level:\n", max_indices)

# Perform element-wise multiplication between the original array and the max indices array
broadcasted_max_indices = np.expand_dims(max_indices, axis=2)
result = array_3d * broadcasted_max_indices
print("\nResult of element-wise multiplication:\n", result)

3D Array:
 [[[ 3  8  2]
  [10  6  9]
  [ 2  2 10]]

 [[ 5  2  9]
  [ 8  4  3]
  [ 1 10  6]]

 [[ 1  9  2]
  [ 5  2  8]
  [ 5  2  1]]]

Indices of maximum values along each depth level:
 [[1 0 2]
 [2 0 1]
 [1 2 0]]

Result of element-wise multiplication:
 [[[ 3  8  2]
  [ 0  0  0]
  [ 4  4 20]]

 [[10  4 18]
  [ 0  0  0]
  [ 1 10  6]]

 [[ 1  9  2]
  [10  4 16]
  [ 0  0  0]]]


##People Data

In [13]:
!gdown 11EdSBWzmuZ3hQD2oVrN2M1LQZwWus5J5

Downloading...
From: https://drive.google.com/uc?id=11EdSBWzmuZ3hQD2oVrN2M1LQZwWus5J5
To: /content/People Data.csv
100% 119k/119k [00:00<00:00, 7.75MB/s]


In [15]:
import pandas as pd
data=pd.read_csv('People Data.csv')
data.head()

Index          User Id First Name Last Name  Gender  \
0      1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1      2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2      3  810Ce0F276Badec     Sheryl    Lowery  Female   
3      4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4      5  9afFEafAe1CBBB9    Lindsey      Rice  Female   

                           Email               Phone Date of birth  \
0            pwarner@example.org        857.139.8239    27-01-2014   
1  fergusonkatherine@example.net                 NaN    26-07-1931   
2            fhoward@example.org       (599)782-0605    25-11-2013   
3          zjohnston@example.com                 NaN    17-11-2012   
4               elin@example.net  (390)417-1635x3010    15-04-1923   

                  Job Title  Salary  
0         Probation officer   90000  
1                    Dancer   80000  
2                      Copy   50000  
3  Counselling psychologist   65000  
4       Biomedical engineer  100000